### ISSUE TITLE
AOT+old tools.reader causing problems using latest ClojureScript

### ISSUE THREAD

**Issue by bbss** [clojupyter/clojupyter#58] opened 2018-02-17 03:43 UTC
Thanks for the great project!

When adding the latest ClojureScript to one of my projects with clojupyter I hit an error related to new syntax added in the Clojure tools.reader. @bhauman, ClojureScript contributor helped me track it down to the use of AOT here.

Let me paste the communication I had with him for context:

```
bbss
So I seem to be hitting this error too, `No reader function for tag Inf`. 
If I look in the `lein deps :tree` I don't see any other dependency that requires it [it = tools.reader]. 
Will AOT dependencies show up there?
I guess this is suspect:
`[ring/ring-core "1.6.1" :exclusions [[org.clojure/tools.reader] [org.clojure/clojure]]]`
bhauman
AOT compiled classes are like a ghost in this case. (edited)
You do need to make sure that the tools.reader in the tree is at least 1.1.0
bbss
Removing the dependency that had that exclusion seems to not give that error and make the `lein figwheel` process crash so that's good!
Yeah, it was! So I guess we found the culprit.
bhauman
which dep was it?
bbss
`[org.clojars.didiercrunch/clojupyter "0.1.3"]`
I'll see if I can fix it by building locally later, and PR.
bhauman
https://github.com/clojupyter/clojupyter/blob/master/project.clj#L25 (edited)
that isn't needed I don't think perhaps file an issue
we should compile a list of the offenders
they could also just bump their tools.reader if they need the AOT
```

I'm not too familiar with the internals of this project and AOT, so don't really know what the purpose of the AOT is. Please let me know if I can help with this.

**Comment by didiercrunch** [comment] 2018-02-18 12:49
Morning barus,

I am afk this weekend.  I will take a look at it monday.

Thanks for reporting the error,

Didier

Quito, time.

**Comment by bbss** [comment] 2018-02-19 08:52
Yeah sure, no rush. It's not something that blocks me.

I've been looking through the source a bit. And understand that AOT is probably used to speed up kernel start-up time, is that right?

**Comment by klausharbo** [comment] 2019-03-26 13:50
I am not sure what issue is described above.  However, I do see that the issue appears to be related to dependency on an old version of `org.clojure/tools.reader` and that Bruce states that it needs to be at lease at v1.1.0.  Since current clojupyter depends on version 1.2.2, I suspect that this issue is likely resolved, so I'm closing the issue.  If this is not correct, do reopen and provide more information how to reproduce the problem, please!

Closed.

-Klaus.

**Closed by klausharbo** 2019-03-26 13:50 UTC
