### ISSUE TITLE
Throws error in Mac M1

### ISSUE THREAD

**Issue by mindaslab** [clojupyter/clojupyter#159] opened 2022-01-26 11:33 UTC
I cot clojupyter installed on Mac M1 Monterey using the following command 

```
conda install -y -c simplect clojupyter
```

But when I try to open a jupyter notebook I get this error:

```
[I 2022-01-25 10:21:54.017 LabApp] Build is up to date
[I 2022-01-25 10:21:57.063 ServerApp] Creating new notebook in
[I 2022-01-25 10:21:57.529 ServerApp] Kernel started: 271c0671-68c9-4ebc-b92d-9d8fe5b86837
[E 04:52:08.886 Clojupyter] c8r.messages -- Invalid message signature
[E 04:52:08.932 Clojupyter] c8r.util-actions --
                                        java.lang.Thread.run              Thread.java:  745
          java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
           java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                         ...
                           clojure.core.async/thread-call/fn                async.clj:  443
                                     clojupyter.zmq/start/fn                  zmq.clj:  108
                                      clojure.core.async/>!!                async.clj:  143
     clojure.core.async.impl.channels.ManyToManyChannel/put!             channels.clj:  143
                    clojure.core.async.impl.channels/chan/fn             channels.clj:  300
                                      clojure.core/map/fn/fn                 core.clj: 2742
                                                         ...
clojupyter.util-actions/wrap-report-and-absorb-exceptions/fn         util_actions.clj:  239
                                          clojure.core/apply                 core.clj:  665
                                                         ...
                                        clojure.core/comp/fn                 core.clj: 2569
         clojupyter.kernel.core/wrap-skip-shutdown-tokens/fn                 core.clj:   83
                                        clojure.core/comp/fn                 core.clj: 2569
                                     clojure.core/partial/fn                 core.clj: 2624
                                                         ...
                 clojure.spec.test.alpha/spec-checking-fn/fn                alpha.clj:  142
                                                         ...
                       clojupyter.messages/fn/frames->jupmsg             messages.clj:  288
java.lang.Exception: Invalid message signature

[E 04:52:09.009 Clojupyter] c8r.util-actions --
                                        java.lang.Thread.run              Thread.java:  745
          java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
           java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                         ...
                           clojure.core.async/thread-call/fn                async.clj:  443
                                     clojupyter.zmq/start/fn                  zmq.clj:  108
                                      clojure.core.async/>!!                async.clj:  143
     clojure.core.async.impl.channels.ManyToManyChannel/put!             channels.clj:  143
                    clojure.core.async.impl.channels/chan/fn             channels.clj:  300
                                      clojure.core/map/fn/fn                 core.clj: 2742
                                                         ...
clojupyter.util-actions/wrap-report-and-absorb-exceptions/fn         util_actions.clj:  239
                                          clojure.core/apply                 core.clj:  665
                                                         ...
                                        clojure.core/comp/fn                 core.clj: 2569
         clojupyter.kernel.core/wrap-skip-shutdown-tokens/fn                 core.clj:   83
                                        clojure.core/comp/fn                 core.clj: 2569
                                     clojure.core/partial/fn                 core.clj: 2624
                                                         ...
                 clojure.spec.test.alpha/spec-checking-fn/fn                alpha.clj:  142
                                                         ...
                       clojupyter.messages/fn/frames->jupmsg             messages.clj:  288
java.lang.Exception: Invalid message signature

Exception in thread "async-thread-macro-11" java.lang.AssertionError: Assert failed: handle-request - internal error (':shell_port' neq '')
```

**Comment by rebcabin** [comment] 2022-09-04 14:01
Definitely fails for me with Jupyter lab 3.4.5 and clojupyter 0.3.3, 0.3.4, 0.3.5 in various complex ways. Tried all three on Mac M1 Pro Max 64 GB RAM

**Comment by krukow** [comment] 2022-09-05 08:30
I will be able to look into this issue this month (I'm expecting an M1 mac arriving)

**Comment by rebcabin** [comment] 2022-09-06 17:44
That'll be great. I want to write test generators for a FOSS Python compiler (lpython.org) with clojure.spec and test.check and have my compiler team (with only passing knowledge of Clojure) collaborate in notebooks.

**Comment by krukow** [comment] 2022-09-21 12:32
Hey @rebcabin @mindaslab -- I've gotten a M1 Max MacBook Pro and I'm unable to reproduce the problem. I've successfully run clojupyter 0.3.5 with jupyter lab 3.4.4:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/3635/191504344-232a2a28-7326-4ab8-acda-385aff9a550b.png">

Can you help me with a simple example to reproduce the problem?

**Comment by krukow** [comment] 2022-10-02 18:25
Please install release 0.3.6 from https://clojars.org/clojupyter.

This is tested and working. 

Closing this issue - please reopen if you can reproduce the problem. If you reopen, please help me with instructions to reproduce from a clean install

**Closed by krukow** 2022-10-02 18:25 UTC
