### ISSUE TITLE
Dead kernel on startup

### ISSUE THREAD

**Issue by AtheistApe** [clojupyter/clojupyter#30] opened 2016-12-21 20:56 UTC
I installed clojupyter according to instructions. But after loading jupyter notebook and creating a new file with the closure kernel, it always ends up with "dead kernel"

**Comment by pdenno** [comment] 2016-12-21 22:06
What is your platform?

**Comment by AtheistApe** [comment] 2016-12-24 04:01
Hi and thanks for the prompt response :-)

My system info is below:


Sincerely,
Gary

**Comment by roryk** [comment] 2016-12-24 05:25
Hi Gary and Peter,

I think the info didn't make it through the email.

**Comment by pdenno** [comment] 2016-12-25 15:00
Hi Rory, 

No, I don't think the attachment got through.

**Comment by AtheistApe** [comment] 2016-12-27 00:18
Hello again,

Not sure why the attachment failed. Anyway, Here is my system info:

OS X El Capitan (Version 10.11.6)

Macbook Pro (15-inch, Mid 2010)
Processor: 2.66 GHz Intel Core i7
Memory: 8 GB 1067 MHz DDR3
Graphics: NVIDIA GeForce GT 330M 512 MB

Gary

**Comment by nilsga** [comment] 2017-01-04 14:36
I'm having the same issue, running with Jupyter notebook 4.3.1 on an AWS EC2 instance. Error log is:

`Message type comm_info_request not handled yet. Exiting`

Any progress on this issue?

**Comment by pdenno** [comment] 2017-01-04 15:29
My platform is almost identical to Gary's (AtheistApe). The difference is probably with the Jupyter version. I'm using Anaconda Python, for which Jupyter is at version 4.1.0 not 4.3.1. Since I need to stick with Anaconda, I'll try 4.3.1 in a VM.

**Comment by pdenno** [comment] 2017-01-04 17:26
I tried a ubuntu VM, which only got me to Jupyter version 4.2.1. It works there. Any pointers on how I might get to version 4.3.1 ?

**Comment by nilsga** [comment] 2017-01-04 18:47
I had the same error with Jupyter 4.2.1, but I managed to upgrade to 4.3.1 by doing a `pip install --upgrade notebook`.

**Comment by nilsga** [comment] 2017-01-04 19:06
I can confirm that it works with notebook 4.1.0 (`pip install notebook==4.1.0`).

**Comment by pdenno** [comment] 2017-01-04 21:54
I don't get an error with 4.2.1 and "pip install --upgrade notebook" doesn't get me to 4.3.1. I using Ubuntu 16.04 LTS. Perhaps that doesn't get refreshed often enough to see 4.3.1. But you say it didn't work on 4.2.1 either. Hmm...

**Comment by nilsga** [comment] 2017-01-05 08:08
Which version of `jupyter-client` do you run? Seems like the `comm_info_request` (https://jupyter-client.readthedocs.io/en/latest/messaging.html#comm-info) message type was introduced in `jupyter-client` 4.1, scanning through the git changelog.

**Comment by pdenno** [comment] 2017-01-05 17:14
> Which version of jupyter-client do you run?

Do you mean jupyter-notebook? I don't run jupyter-client.  I think the versioning you are referring to for comm_info_request refers to the python jupyter_client API . 

I see now that the version of jupyter-notebook is not the same as that of jupyter (the thing that you can call with argument 'notebook'). jupyter-notebook is version 4.3.1 on the Ubuntu VM and 4.1.0 under Anaconda. So I have run under 4.3.1 and have not seen the comm_info_request error.

I might be confused as to what is going on here. Sorry.

**Comment by nilsga** [comment] 2017-01-05 19:06
Right, I might have been looking at the wrong place. But looking at the jupyter server and kernel code, it seems like this is a message that was introduced in jupyter 4.1 https://github.com/jupyter/notebook/commit/c451342c81a546f498d7330bf8f6937ab02c78c9

**Comment by nilsga** [comment] 2017-01-05 19:13
Not sure if it makes a difference, but I run it through a docker image based on this image: https://hub.docker.com/r/jupyter/singleuser/

Basically extended the image and installed the kernel within it.

**Comment by nilsga** [comment] 2017-01-05 21:49
Very strange. Guess it has to be something with the base jupyterhub docker image then...

**Comment by nilsga** [comment] 2017-01-05 21:52
I don't get it though. Shouldn't the message be handled still? And it does look a lot like this issue, that is supposed to be closed: https://github.com/roryk/clojupyter/issues/19

**Comment by pdenno** [comment] 2017-01-05 22:32
If I'm reading that correctly, it seems like they started off talking about `comm_info_request` but then discussed auto-completion. The message is not handled: 

````clojure
(defn configure-shell-handler [shell-socket iopub-socket signer nrepl-transport]
  (let [execute-request (execute-request-handler shell-socket iopub-socket nrepl-transport)]
    (fn [message]
      (let [msg-type (get-in message [:header :msg_type])]
        (case msg-type
          "kernel_info_request" (kernel-info-reply message shell-socket signer)
          "execute_request" (execute-request message signer)
          "history_request" (history-reply message signer)
          "shutdown_request" (shutdown-reply message signer)
          "comm_open" (immediately-close-comm message shell-socket signer)
          "is_complete_request" (is-complete-info-reply message shell-socket signer)
          "complete_request" (complete-reply message signer)
          (do
            (println "Message type" msg-type "not handled yet. Exiting.")
            (println "Message dump:" message)
            (System/exit -1)))))))
````

It might not be too hard to implement, but I can't do it without seeing the message. You might add some code to the case statement above to print the message map. See what you get. It might even run fine if you just add a clause to the case `"comm_info" (pprint message)` then do make and make install.

**Comment by pdenno** [comment] 2017-01-05 22:59
Looking at the code above, I wonder why we give up so easily `(System/exit -1)`. Reading the jupyter-client spec, I get the sense we might see more message types we haven't yet implemented.  Maybe the best thing to do is just print a warning each time we get one. The client can time out or whatever it wants.

**Comment by nilsga** [comment] 2017-01-06 07:28
Message dump:

```
{:idents (), :delimiter <IDS|MSG>, :signature 937209f2144276aeec6d60c3d512f69e8f5e4948140dfd30d8b932a8582cb628, :header {:msg_id A3AE7A37DB70487D8B76225750C44160, :session C69CC6036AF745DA85F75B96108F52F2, :username username, :version 5.0, :msg_type comm_info_request}, :parent-header {}, :content {:target_name jupyter.widget}}
```

**Comment by nilsga** [comment] 2017-01-06 08:01
Simply ignoring the message prevents the kernel from crashing, but I get a message `Timeout waiting for kernel_info reply from 217480a8-d335-496a-b6bc-00da3f215844`

**Comment by nilsga** [comment] 2017-01-06 08:04
Reading the docs about [Comms](https://jupyter-notebook.readthedocs.io/en/latest/comms.html), I get the feeling that this might be extension related. It explicitly refers to `ipywidget`, which is exactly what is the target of the message in question.

**Comment by nilsga** [comment] 2017-01-06 10:47
If I should take a guess, this (from the base` jupyter/scipy-notebook` image) might be the difference that triggers the error: `RUN jupyter nbextension enable --py widgetsnbextension --sys-prefix`

**Comment by klausharbo** [comment] 2019-03-22 21:43
This is fixed on the `develop` branch: The clojupyter kernel no longer terminates when it receives an unknown message.

**Closed by klausharbo** 2019-03-22 21:43 UTC
Labels: bug
