### ISSUE TITLE
0.2.3: syntax error on `make install`[Imagemagick needed to install Clojupyter]

### ISSUE THREAD

**Issue by iwinux** [clojupyter/clojupyter#103] opened 2019-10-23 02:09 UTC
Env: Leiningen 2.9.1 on Java 1.8.0_222 OpenJDK 64-Bit Server VM

Output of `make install`:

```sh
Created /home/ld-sgdev/lingbo_peng/clojupyter/target/clojupyter-0.2.3.jar
Created /home/ld-sgdev/lingbo_peng/clojupyter/target/clojupyter-0.2.3-standalone.jar
lein clojupyter install
Syntax error (NoClassDefFoundError) compiling at (/tmp/form-init123840598411660495.clj:1:72).
io/simplect/compose$χ (wrong name: io/simplect/compose$λ)
```

Is there any missed steps prior to `make install`?

**Comment by klausharbo** [comment] 2019-10-23 07:36
I am not aware of any prerequisites, except building your own kernel requires a working Clojure setup, which you seem to have.  To check I just cloned the `clojupyter/clojupyter` repo and did a `make install` on my Mac, it built and installed just fine.

It looks like the error occurs compiling `io.simplect.compose` where some functions have Greek letters as names (λ,Γ, γ, π, Π, χ) - the reported problem seems to relate to χ (Greek lowercase 'chi').  Could it be related to something in your locale/language setup?

If you are simply interested in trying out Clojupyter the CONDA usage scenario (cf. [Usage Scenarios](https://github.com/clojupyter/clojupyter/blob/master/doc/usage-scenarios.md)) might also work for you (you don't need to compile Clojupyter to use `conda install`).

-Klaus.

--
The env I tried: 

```
> lein --version
Leiningen 2.9.0 on Java 1.8.0_192 OpenJDK 64-Bit Server VM
> uname -a
Darwin locke-2.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by iwinux** [comment] 2019-10-23 08:07
Weird, is `io.simplect.compose` introduced in 0.2.3? `make install` on 0.2.2 branch works without any problem.

**Comment by iwinux** [comment] 2019-10-23 08:25
You're right about locale (I'm building it in Linux). After forcing it to `en_US.UTF-8`, the error changed to:

```
lein clojupyter install
(-main) Error occurred: clojure.lang.ExceptionInfo: Internal error: Bad install-env {:install-env {:local/resource-map {"clojupyter/assets/conda-build/pre-unlink.sh" #object[java.net.URL 0x3408f695 "file:/root/clojupyter/resources/clojupyter/assets/conda-build/pre-unlink.sh"], "clojupyter/assets/conda-build/post-link.bat" #object[java.net.URL 0x2b6a0ea9 "file:/root/clojupyter/resources/clojupyter/assets/conda-build/post-link.bat"], "clojupyter/assets/logo-64x64.png" #object[java.net.URL 0x4dde8976 "file:/root/clojupyter/resources/clojupyter/assets/logo-64x64.png"], "clojupyter/assets/conda-build/post-link.sh" #object[java.net.URL 0x4887de2b "file:/root/clojupyter/resources/clojupyter/assets/conda-build/post-link.sh"]}, :version/version-map #:version{:major 0, :minor 2, :incremental 3, :lein-v-raw "v0.2.2-16-gd11a"}, :local/jarfiles (#object[java.io.File 0x3b4825f0 "/root/clojupyter/target/clojupyter-0.2.3-standalone.jar"]), :local/user-homedir #object[java.io.File 0x40ac6b76 "/root"], :local/filemap #filemap{#object[java.io.File 0x3b4825f0 "/root/clojupyter/target/clojupyter-0.2.3-standalone.jar"]
 :filetype/file,
 #object[java.io.File 0x640cc04b "/root/.local/share/jupyter/kernels"]
 nil,
 #object[java.io.File 0x3520963d "/usr/local/share/jupyter/kernels"]
 nil}, :local/logo-resource "clojupyter/assets/logo-64x64.png", :local/user-kernel-dir #object[java.io.File 0x640cc04b "/root/.local/share/jupyter/kernels"], :local/host-kernel-dir #object[java.io.File 0x3520963d "/usr/local/share/jupyter/kernels"], :local/convert-exe nil, :local/default-ident "clojupyter-0.2.3v0.2.2-16-gd11a", :local/installed-kernels {}}, :explain-str "nil - failed: (π instance? java.io.File) in: [:local/convert-exe] at: [:local/convert-exe] spec: :local/file\n", :msg "Internal error: Bad install-env"}
make: *** [Makefile:11: install] Error 1
```

Still no idea what is going on....

**Comment by klausharbo** [comment] 2019-10-23 08:28
Yes, it was, compare [project.clj@0.2.2](https://github.com/clojupyter/clojupyter/blob/release/0.2.2/project.clj) with [project.clj@0.2.3](https://github.com/clojupyter/clojupyter/blob/release/0.2.3/project.clj).

**Comment by klausharbo** [comment] 2019-10-23 08:42
I think I see what is going on: Clojupyter is complaining that it cannot find `convert.exe` which it needs customize icons.  The `--skip-icon-tags` tells it to not customize the tag, so try `lein clojupyter install --skip-icon-tags`...

**Comment by klausharbo** [comment] 2019-10-23 08:43
This is an error, btw.

**Comment by iwinux** [comment] 2019-10-23 08:43
Haha, nice catch. Installing `imagemagick` fixed it. Thanks very much!

**Comment by klausharbo** [comment] 2019-10-23 08:53
Let's keep this one open until the issue is fixed :-)

**Comment by klausharbo** [comment] 2019-11-26 21:11
As can be seen above there's at least a workaround for this issue allowing you to install Clojupyter *without* having to install Imagemagick which is not necessarily always possible.  The issue outlined here was essentially that Clojupyter installs would *always* fail if it could not find the `convert` executable from Imagemagick, even if it was not needed.  By default it was needed, but the `--skip-icon-tags` allows you to leave the icons untouched.  Clearly you should be able install without having Imagemagick installed when you specify `--skip-icon-tags`.  This workaround accomplishes this. 

I don't consider the issue fully addressed, though, because I think this suggests that the default ought to be skipping icon customizations by default, and using a flag like `--customize-icons` to specify when you do want that.  That is a somewhat larger change, especially because the documentation is affected; and that is more than I am prepared to devote to the issue right now.  So, for now, there's a workaround available on `master`, available for anyone encountering this difficulty.

The workaround will be included in the next release.

**Comment by vikeri** [comment] 2019-12-10 21:09
I had the same issue running Clojupyter in a Docker container. After installing imagemagick it works.

**Comment by klausharbo** [comment] 2019-12-11 07:07
I think it's probably better to keep the issue open until the fix is in a release.

**Comment by klausharbo** [comment] 2020-01-06 06:49
Clojupyter 0.3.0beta1 includes the fix for this bug.  Closed.

**Closed by klausharbo** 2020-01-06 06:49 UTC
Labels: Resolved, bug
