### ISSUE TITLE
Kernel restarting

### ISSUE THREAD

**Issue by gpasa** [clojupyter/clojupyter#162] opened 2022-03-16 08:38 UTC
Hi,
I installed clojupyter as a jupyter kernel, but it crashes regularly. Looking at the log it says

[E 08:10:18.171 Clojupyter] c8r.kernel.handle-event-process -- 
                                                java.lang.Thread.run               Thread.java:  833
                  java.util.concurrent.ThreadPoolExecutor$Worker.run   ThreadPoolExecutor.java:  635
                   java.util.concurrent.ThreadPoolExecutor.runWorker   ThreadPoolExecutor.java: 1136
                                                                 ...                                
                                   clojure.core.async/thread-call/fn                 async.clj:  484
      clojupyter.kernel.handle-event-process/start-channel-thread/fn  handle_event_process.clj:   61
            clojupyter.kernel.handle-event-process/run-dispatch-loop  handle_event_process.clj:   52
clojupyter.kernel.handle-event-process/handle-event-or-channel-error  handle_event_process.clj:   35
                        clojupyter.kernel.handle-event/handle-event!          handle_event.clj:   86
                   clojupyter.kernel.handle-event/calculate-response          handle_event.clj:   81
                                                                 ...                                
                                   clojupyter.kernel.handle-event/fn          handle_event.clj:   65
                 clojupyter.kernel.handle-event.ops/call-interceptor                   ops.clj:   87
                 clojupyter.kernel.handle-event.ops/call-interceptor                   ops.clj:   89
                               io.pedestal.interceptor.chain/execute                 chain.clj:  389
                               io.pedestal.interceptor.chain/execute                 chain.clj:  379
                             io.pedestal.interceptor.chain/enter-all                 chain.clj:  235
                           io.pedestal.interceptor.chain/process-all                 chain.clj:  186
                                                                 ...                                
                                         clojure.core/with-bindings*                  core.clj: 1973 (repeats 2 times)
                                                  clojure.core/apply                  core.clj:  665
                                                                 ...                                
                        io.pedestal.interceptor.chain/process-all/fn                 chain.clj:  188
              io.pedestal.interceptor.chain/process-all-with-binding                 chain.clj:  171
                                 io.pedestal.interceptor.chain/try-f                 chain.clj:   54
                                             clojure.core/partial/fn                  core.clj: 2631
                  clojupyter.kernel.handle-event.ops/call-if-msgtype                   ops.clj:   44
             clojupyter.kernel.handle-event.inspect/ic*inspect-enter               inspect.clj:   43
                 clojupyter.kernel.handle-event.inspect/inspect-info               inspect.clj:   38
                     clojupyter.kernel.handle-event.inspect/token-at               inspect.clj:   32
                                                clojure.core/re-find                  core.clj: 4898
                                             clojure.core/re-matcher                  core.clj: 4856
                                     java.util.regex.Pattern.matcher              Pattern.java: 1134
                                      java.util.regex.Matcher.<init>              Matcher.java:  252
                                       java.util.regex.Matcher.reset              Matcher.java:  415
                               java.util.regex.Matcher.getTextLength              Matcher.java: 1769
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
    clojure.lang.ExceptionInfo: java.lang.NullPointerException in Interceptor :clojupyter.kernel.handle-event.inspect/ic*inspect - Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
    exception-type: :java.lang.NullPointerException
      execution-id: 8
       interceptor: :clojupyter.kernel.handle-event.inspect/ic*inspect
             stage: :enter

Any clue ?
I'm running with java OpenJDK 17 GraalVM CE 22.0.0.2 with last git zip

**Comment by franks42** [comment] 2022-03-27 02:01
I'm having a similar issue with openjdk 17.0.2 and the "0.3.3-SNAPSHOT" off the head of the master branch:

[I 2022-03-26 18:52:21.729 LabApp] Build is up to date
[I 2022-03-26 18:52:40.180 ServerApp] Creating new notebook in
[I 2022-03-26 18:52:40.418 ServerApp] Kernel started: d85dcd49-1019-4dcc-86ae-723d61670e86
[I 2022-03-26 18:52:42.821 ServerApp] Adapting from protocol version 5.2 (kernel d85dcd49-1019-4dcc-86ae-723d61670e86) to 5.3 (client).
[I 2022-03-26 18:52:42.840 ServerApp] Adapting from protocol version 5.2 (kernel d85dcd49-1019-4dcc-86ae-723d61670e86) to 5.3 (client).
[I 2022-03-26 18:52:42.840 ServerApp] Starting buffering for d85dcd49-1019-4dcc-86ae-723d61670e86:107cbc55-cb96-44db-8d62-8e221874ad28
[I 2022-03-26 18:52:42.857 ServerApp] Adapting from protocol version 5.2 (kernel d85dcd49-1019-4dcc-86ae-723d61670e86) to 5.3 (client).
[E 01:52:42.851 Clojupyter] c8r.kernel.handle-event-process --
                                                java.lang.Thread.run               Thread.java:  833
                  java.util.concurrent.ThreadPoolExecutor$Worker.run   ThreadPoolExecutor.java:  635
                   java.util.concurrent.ThreadPoolExecutor.runWorker   ThreadPoolExecutor.java: 1136
                                                                 ...
                                   clojure.core.async/thread-call/fn                 async.clj:  484
      clojupyter.kernel.handle-event-process/start-channel-thread/fn  handle_event_process.clj:   61
            clojupyter.kernel.handle-event-process/run-dispatch-loop  handle_event_process.clj:   52
clojupyter.kernel.handle-event-process/handle-event-or-channel-error  handle_event_process.clj:   31
clojure.lang.ExceptionInfo: Invalid msgtype for port :control_port: kernel_info_request
    channel-port: :control_port
         msgtype: "kernel_info_request"
     req-message: {:header
                   {:msg_id "c6a104c2-0b4b-4112-b0ff-20079b5cea84_85116_1",
                    :msg_type "kernel_info_request",
                    :username "franksiebenlist",
                    :session "c6a104c2-0b4b-4112-b0ff-20079b5cea84",
                    :date "2022-03-27T01:52:42.842297Z",
                    :version "5.3"},
                   :parent-header {},
                   :metadata {},
                   :content {},
                   :preframes
                   #Preframes[[:hash/0xd5f317a3] :hash/0x3ecbec84 :hash/0x2c290cb2],
                   :buffers #Buffers[]}

Exception in thread "async-thread-macro-10" clojure.lang.ExceptionInfo: Invalid msgtype for port :control_port: kernel_info_request {:req-message {:header {:msg_id "c6a104c2-0b4b-4112-b0ff-20079b5cea84_85116_1", :msg_type "kernel_info_request", :username "franksiebenlist", :session "c6a104c2-0b4b-4112-b0ff-20079b5cea84", :date "2022-03-27T01:52:42.842297Z", :version "5.3"}, :parent-header {}, :metadata {}, :content {}, :preframes #Preframes[[:hash/0xd5f317a3] :hash/0x3ecbec84 :hash/0x2c290cb2], :buffers #Buffers[]}, :msgtype "kernel_info_request", :channel-port :control_port}
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invokeStatic(handle_event_process.clj:31)
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invoke(handle_event_process.clj:16)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invokeStatic(handle_event_process.clj:52)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invoke(handle_event_process.clj:40)
	at clojupyter.kernel.handle_event_process$start_channel_thread$fn__28480.invoke(handle_event_process.clj:61)
	at clojure.core.async$thread_call$fn__5910.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
...

goes into a loop of restarting with same exception...

**Comment by krukow** [comment] 2022-04-15 06:21
@gpasa @franks42 -- which version of jupyter (lab) are you using?

**Comment by krukow** [comment] 2022-04-15 06:30
And thanks for reporting :)

**Comment by gpasa** [comment] 2022-04-15 06:33
I’m running version 3.3.2 with python 3.10 in a virtualenv. It is the only kernel that has that behavior.

**Comment by krukow** [comment] 2022-04-15 11:28
Hey both.
Could you both try running this version of clojupyter:

Leiningen/Boot
`[clojupyter "0.3.3-alpha2"]`

Clojure CLI/deps.edn
`clojupyter/clojupyter {:mvn/version "0.3.3-alpha2"}`

I have that working with latest jupyter lab (3.3.3).

**Comment by krukow** [comment] 2022-04-15 13:01
If that does not work, please try version 0.3.3

Leiningen/Boot: `[clojupyter "0.3.3"]`

Clojure CLI/deps.edn `clojupyter/clojupyter {:mvn/version "0.3.3"}`

**Comment by gpasa** [comment] 2022-04-15 16:50
I downloaded version 0.3.4 and it seems to work. I've been able to run the example you gave on the initial page.

Thanks !

**Comment by gpasa** [comment] 2022-04-15 17:01
Some occasional restart remains.
Here is the last one

0) 3.67ms
[E 16:57:34.698 Clojupyter] c8r.kernel.handle-event-process -- 
                                                java.lang.Thread.run               Thread.java:  829
                  java.util.concurrent.ThreadPoolExecutor$Worker.run   ThreadPoolExecutor.java:  628
                   java.util.concurrent.ThreadPoolExecutor.runWorker   ThreadPoolExecutor.java: 1128
                                                                 ...                                
                                   clojure.core.async/thread-call/fn                 async.clj:  484
      clojupyter.kernel.handle-event-process/start-channel-thread/fn  handle_event_process.clj:   61
            clojupyter.kernel.handle-event-process/run-dispatch-loop  handle_event_process.clj:   52
clojupyter.kernel.handle-event-process/handle-event-or-channel-error  handle_event_process.clj:   35
                        clojupyter.kernel.handle-event/handle-event!          handle_event.clj:   86
                   clojupyter.kernel.handle-event/calculate-response          handle_event.clj:   81
                                                                 ...                                
                                   clojupyter.kernel.handle-event/fn          handle_event.clj:   65
                 clojupyter.kernel.handle-event.ops/call-interceptor                   ops.clj:   87
                 clojupyter.kernel.handle-event.ops/call-interceptor                   ops.clj:   89
                               io.pedestal.interceptor.chain/execute                 chain.clj:  389
                               io.pedestal.interceptor.chain/execute                 chain.clj:  379
                             io.pedestal.interceptor.chain/enter-all                 chain.clj:  235
                           io.pedestal.interceptor.chain/process-all                 chain.clj:  186
                                                                 ...                                
                                         clojure.core/with-bindings*                  core.clj: 1973 (repeats 2 times)
                                                  clojure.core/apply                  core.clj:  665
                                                                 ...                                
                        io.pedestal.interceptor.chain/process-all/fn                 chain.clj:  188
              io.pedestal.interceptor.chain/process-all-with-binding                 chain.clj:  171
                                 io.pedestal.interceptor.chain/try-f                 chain.clj:   54
                                             clojure.core/partial/fn                  core.clj: 2631
                  clojupyter.kernel.handle-event.ops/call-if-msgtype                   ops.clj:   44
             clojupyter.kernel.handle-event.inspect/ic*inspect-enter               inspect.clj:   43
                 clojupyter.kernel.handle-event.inspect/inspect-info               inspect.clj:   38
                     clojupyter.kernel.handle-event.inspect/token-at               inspect.clj:   32
                                                clojure.core/re-find                  core.clj: 4898
                                             clojure.core/re-matcher                  core.clj: 4856
                                     java.util.regex.Pattern.matcher              Pattern.java: 1133
                                      java.util.regex.Matcher.<init>              Matcher.java:  253
                                       java.util.regex.Matcher.reset              Matcher.java:  416
                               java.util.regex.Matcher.getTextLength              Matcher.java: 1770
java.lang.NullPointerException: 
    clojure.lang.ExceptionInfo: java.lang.NullPointerException in Interceptor :clojupyter.kernel.handle-event.inspect/ic*inspect - 
    exception-type: :java.lang.NullPointerException
      execution-id: 79
       interceptor: :clojupyter.kernel.handle-event.inspect/ic*inspect
             stage: :enter

Exception in thread "async-thread-macro-11" clojure.lang.ExceptionInfo: java.lang.NullPointerException in Interceptor :clojupyter.kernel.handle-event.inspect/ic*inspect -  {:execution-id 79, :stage :enter, :interceptor :clojupyter.kernel.handle-event.inspect/ic*inspect, :exception-type :java.lang.NullPointerException, :exception #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [java.util.regex.Matcher getTextLength "Matcher.java" 1770]}]
 :trace
 [[java.util.regex.Matcher getTextLength "Matcher.java" 1770]
  [java.util.regex.Matcher reset "Matcher.java" 416]
  [java.util.regex.Matcher <init> "Matcher.java" 253]
  [java.util.regex.Pattern matcher "Pattern.java" 1133]
  [clojure.core$re_matcher invokeStatic "core.clj" 4856]
  [clojure.core$re_find invokeStatic "core.clj" 4898]
  [clojure.core$re_find invoke "core.clj" 4898]
  [clojupyter.kernel.handle_event.inspect$token_at invokeStatic "inspect.clj" 32]
  [clojupyter.kernel.handle_event.inspect$token_at invoke "inspect.clj" 22]
  [clojupyter.kernel.handle_event.inspect$inspect_info invokeStatic "inspect.clj" 38]
  [clojupyter.kernel.handle_event.inspect$inspect_info invoke "inspect.clj" 34]
  [clojupyter.kernel.handle_event.inspect$ic_STAR_inspect_enter invokeStatic "inspect.clj" 43]
  [clojupyter.kernel.handle_event.inspect$ic_STAR_inspect_enter invoke "inspect.clj" 42]
  [clojupyter.kernel.handle_event.ops$call_if_msgtype invokeStatic "ops.clj" 44]
  [clojupyter.kernel.handle_event.ops$call_if_msgtype invoke "ops.clj" 41]
  [clojure.core$partial$fn__5841 invoke "core.clj" 2631]
  [io.pedestal.interceptor.chain$try_f invokeStatic "chain.clj" 54]
  [io.pedestal.interceptor.chain$try_f invoke "chain.clj" 44]
  [io.pedestal.interceptor.chain$process_all_with_binding invokeStatic "chain.clj" 171]
  [io.pedestal.interceptor.chain$process_all_with_binding invoke "chain.clj" 146]
  [io.pedestal.interceptor.chain$process_all$fn__21387 invoke "chain.clj" 188]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1973]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1973]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [io.pedestal.interceptor.chain$process_all invokeStatic "chain.clj" 186]
  [io.pedestal.interceptor.chain$process_all invoke "chain.clj" 182]
  [io.pedestal.interceptor.chain$enter_all invokeStatic "chain.clj" 235]
  [io.pedestal.interceptor.chain$enter_all invoke "chain.clj" 229]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 379]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 352]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 389]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 352]
  [clojupyter.kernel.handle_event.ops$call_interceptor invokeStatic "ops.clj" 89]
  [clojupyter.kernel.handle_event.ops$call_interceptor invoke "ops.clj" 85]
  [clojupyter.kernel.handle_event.ops$call_interceptor invokeStatic "ops.clj" 87]
  [clojupyter.kernel.handle_event.ops$call_interceptor invoke "ops.clj" 85]
  [clojupyter.kernel.handle_event$fn__28339 invokeStatic "handle_event.clj" 65]
  [clojupyter.kernel.handle_event$fn__28339 invoke "handle_event.clj" 65]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [clojupyter.kernel.handle_event$calculate_response invokeStatic "handle_event.clj" 81]
  [clojupyter.kernel.handle_event$calculate_response invoke "handle_event.clj" 79]
  [clojupyter.kernel.handle_event$handle_event_BANG_ invokeStatic "handle_event.clj" 86]
  [clojupyter.kernel.handle_event$handle_event_BANG_ invoke "handle_event.clj" 83]
  [clojupyter.kernel.handle_event_process$handle_event_or_channel_error invokeStatic "handle_event_process.clj" 35]
  [clojupyter.kernel.handle_event_process$handle_event_or_channel_error invoke "handle_event_process.clj" 16]
  [clojupyter.kernel.handle_event_process$run_dispatch_loop invokeStatic "handle_event_process.clj" 52]
  [clojupyter.kernel.handle_event_process$run_dispatch_loop invoke "handle_event_process.clj" 40]
  [clojupyter.kernel.handle_event_process$start_channel_thread$fn__28475 invoke "handle_event_process.clj" 61]
  [clojure.core.async$thread_call$fn__5910 invoke "async.clj" 484]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 628]
  [java.lang.Thread run "Thread.java" 829]]}}
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:35)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:57)
	at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:44)
	at io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic(chain.clj:171)
	at io.pedestal.interceptor.chain$process_all_with_binding.invoke(chain.clj:146)
	at io.pedestal.interceptor.chain$process_all$fn__21387.invoke(chain.clj:188)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at io.pedestal.interceptor.chain$process_all.invokeStatic(chain.clj:186)
	at io.pedestal.interceptor.chain$process_all.invoke(chain.clj:182)
	at io.pedestal.interceptor.chain$enter_all.invokeStatic(chain.clj:235)
	at io.pedestal.interceptor.chain$enter_all.invoke(chain.clj:229)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:379)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:389)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at clojupyter.kernel.handle_event.ops$call_interceptor.invokeStatic(ops.clj:89)
	at clojupyter.kernel.handle_event.ops$call_interceptor.invoke(ops.clj:85)
	at clojupyter.kernel.handle_event.ops$call_interceptor.invokeStatic(ops.clj:87)
	at clojupyter.kernel.handle_event.ops$call_interceptor.invoke(ops.clj:85)
	at clojupyter.kernel.handle_event$fn__28339.invokeStatic(handle_event.clj:65)
	at clojupyter.kernel.handle_event$fn__28339.invoke(handle_event.clj:65)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at clojupyter.kernel.handle_event$calculate_response.invokeStatic(handle_event.clj:81)
	at clojupyter.kernel.handle_event$calculate_response.invoke(handle_event.clj:79)
	at clojupyter.kernel.handle_event$handle_event_BANG_.invokeStatic(handle_event.clj:86)
	at clojupyter.kernel.handle_event$handle_event_BANG_.invoke(handle_event.clj:83)
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invokeStatic(handle_event_process.clj:35)
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invoke(handle_event_process.clj:16)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invokeStatic(handle_event_process.clj:52)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invoke(handle_event_process.clj:40)
	at clojupyter.kernel.handle_event_process$start_channel_thread$fn__28475.invoke(handle_event_process.clj:61)
	at clojure.core.async$thread_call$fn__5910.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at clojure.core$re_matcher.invokeStatic(core.clj:4856)
	at clojure.core$re_find.invokeStatic(core.clj:4898)
	at clojure.core$re_find.invoke(core.clj:4898)
	at clojupyter.kernel.handle_event.inspect$token_at.invokeStatic(inspect.clj:32)
	at clojupyter.kernel.handle_event.inspect$token_at.invoke(inspect.clj:22)
	at clojupyter.kernel.handle_event.inspect$inspect_info.invokeStatic(inspect.clj:38)
	at clojupyter.kernel.handle_event.inspect$inspect_info.invoke(inspect.clj:34)
	at clojupyter.kernel.handle_event.inspect$ic_STAR_inspect_enter.invokeStatic(inspect.clj:43)
	at clojupyter.kernel.handle_event.inspect$ic_STAR_inspect_enter.invoke(inspect.clj:42)
	at clojupyter.kernel.handle_event.ops$call_if_msgtype.invokeStatic(ops.clj:44)
	at clojupyter.kernel.handle_event.ops$call_if_msgtype.invoke(ops.clj:41)
	at clojure.core$partial$fn__5841.invoke(core.clj:2631)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54)
	... 39 more
[I 2022-04-15 18:57:36.478 SingleUserLabApp restarter:75] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2022-04-15 18:57:36.478 SingleUserLabApp handlers:754] kernel a074e7cf-8fe8-454d-8c51-3738363113fa restarted

**Comment by krukow** [comment] 2022-04-15 18:56
@gpasa did you mean version 0.3.3?

Also can you help me reproduce this problem?

**Comment by gpasa** [comment] 2022-04-15 19:07
I selected the branch 0.3.4 (maybe for now it is just the same as 0.3.3) and it seems pretty stable. It just crashed once, but since then it doesn't move.

**Comment by weidtn** [comment] 2022-06-16 18:06
Can you release 0.3.3 to conda?

**Comment by krukow** [comment] 2022-06-17 07:41
@klausharbo @nighcoder I can't get the conda release script to work - could you say a few words/document how the release process works (maybe I can script it using GitHub actions then)?

**Comment by nighcoder** [comment] 2022-06-17 15:40
@krukow, I'm not a regular conda user, but I have a VM setup for testing conda building that I used when working on 0.4.0. What branch are you trying to build, so I can test it in on of my VMs?

Afaik, to release a conda version, you need to build a conda package and upload it to a conda channel. The build process uses standard scripts `build`, `pre-unlink` and `post-link` which are ran at specific points in time during the build process. You can find the ones currently used by clojupyter in `resources/clojupyter/assets/conda-build`.

At which step are you having problems?

**Comment by klausharbo** [comment] 2022-06-17 15:45
I took quite detailed notes while doing releases, here's a the one for 0.3.2.  It's very terse, as the intended reader was a future version of me, but I think it could make sense to others as well.  I'm quite rusty but happy to clarify questions regarding it if I can.  See attachment.

[clojupyter-release-process-notes--2020-03-01--0.3.2.1.html.tar.gz](https://github.com/clojupyter/clojupyter/files/8928900/clojupyter-release-process-notes--2020-03-01--0.3.2.1.html.tar.gz)

**Comment by dustingetz** [comment] 2022-08-13 20:02
I had a different exception related to sqllite but fixed it by upgrading my project to `3.39.2.0` (latest sqllite-jdbc as of this writing) from `org.xerial/sqlite-jdbc {:mvn/version "3.36.0.3"}`

**Comment by krukow** [comment] 2022-08-15 12:32
I've pushed a release of 0.3.5 from https://github.com/clojupyter/clojupyter/tree/v0.3.5 - could you all see if this works for you?

**Comment by rebcabin** [comment] 2022-09-04 14:05
All three versions, 0.3.3, 0.3.4, and 0.3.5 fail for me on Mac M1. Please see my comment in Issue #159 .

**Comment by krukow** [comment] 2022-10-02 18:26
@rebcabin 

Please install release 0.3.6 from https://clojars.org/clojupyter.

This is tested and working. 

Closing this issue - please reopen if you can reproduce the problem. If you reopen, please help me with instructions to reproduce from a clean install

**Closed by krukow** 2022-10-02 18:26 UTC

**Comment by rebcabin** [comment] 2022-10-04 12:17
Lovely! Thank you!

One remaining problem: the Vega Light demo in Jupyter-Lab doesn't display anything. I'm not reopening the issue because I don't need this functionality, but I thought you'd like to know. 

<img width="1473" alt="Screen Shot 2022-10-04 at 5 15 27 AM" src="https://user-images.githubusercontent.com/207047/193817075-dbb05d33-881f-496a-8642-8c4b92f17ef4.png">

**Comment by krukow** [comment] 2022-10-05 09:30
Thanks for reporting @rebcabin  - tracking issue created: https://github.com/clojupyter/clojupyter/issues/166
